
---
#********************************************************************************
# Script Name: disable-user-linux.yml
# Description: Use this playbook to lock as well as disable / expire the specified user account
# Author: Raghu Sundaram
# Organization: Harman
#********************************************************************************
# Ansible playbook to lock and disable / expire user account
#
#

- name: Disable eve user account in Windows
  hosts: all
  become_user: root
  become: true
  gather_facts: no
  tasks: 
   - name: Disable the eve account
     win_shell : Disable-LocalUser -Name "eve"
     register: disable user