---
#**************************************************************

# Script Name: dmsp_vm_reboot.yaml

# Description: This playbook will reboot the VMs

# Author: Raghu Sundaram

# Organization: Harman

#**************************************************************
- name: Reboot the VMs
  hosts: reboot
  gather_facts: false
  become_user: root
  become: true
  ignore_errors: yes
  vars: 
    ansible_remote_tmp: /tmp
  tasks: 
    - name: Reboot
      reboot: 
       msg: "Reboot required for updated kernel"
#      when: ansible_hostname is not search('pmsplb|awx|omsp|odia|cmspclearcase|tvm')