---
#**************************************************************

# Script Name: fix_yum_rhel8_dmsp.yml

# Description: This playbook will re-register RH VMs with the Redhat Satellite

# Author: Raghu Sundaram

# Organization: Harman

#**************************************************************
- name: Re-Register the RH VMs with Redhat Satellite
  hosts: all
  strategy: free
  gather_facts: false
  become_user: root
  become: true
  tasks: 
    - name: fix yum
      shell: bash -c "$(curl -fsSL 10.1.214.33:80/devReg.sh)"
      register: yum_output
      async: 300
      poll: 60

    - name: Show output
      debug:
       var: yum_output.stdout_lines