---
# This playbook is to check for updates in both RHEL and Ubuntu VMs.
# playbook name: Linux_Register_Dev_Satellite_Patching-v3.yaml
# Author: Raghu Sundaram
# Organization: Harman

- name: Install updates in RedHat based VMs
  hosts: rhel
  become_user: root
  become: true
  gather_facts: false
  ignore_errors: true
  vars: 
    ansible_remote_tmp: /tmp
  tasks:
    - name: Check /boot freespace
      shell: df /boot --output\=avail | tail -1
      register: boot_freespace
      check_mode: false
    - name: Salt repo fix
      shell: bash -c "$(curl -fsSL 10.1.60.242:80/updateSaltRepo.sh)"        
      check_mode: no
    - name: Install kernel updates
      yum: 
       name: 'kernel'
       state: latest
       update_cache: yes
       update_only: yes
      tags: kernel
      ignore_errors: true
#      when: boot_freespace.stdout_lines|float is gt 80000
      async: 1800
      poll: 300
      register: kernel_update_rhel_status
    - name: Install regular updates on RH based VMs
      yum: 
       name: '*'
       state: latest
       update_cache: no
       update_only: yes
       exclude: salt*
      tags: regular 
      ignore_errors: true
      async: 1800
      poll: 300     
      register: regular_updates_rhel_status
    - name: Log Patch update status
      lineinfile:
        line: "{{regular_updates_rhel_status.changed}} - {{regular_updates_rhel_status.msg}}"
        path: /tmp/patch_status.log
        create: yes