---
# This playbook is to install updates in both RHEL and Ubuntu VMs.
# playbook name: Linux_Register_Corp_Satellite_Patching-v3.yaml
# Author: Raghu Sundaram
# Organization: Harman

- name: Install updates in RedHat based VMs
  hosts: all
  become_user: root
  become: true
  ignore_errors: true
  vars: 
    ansible_remote_tmp: /tmp
  tasks:
    - name: Refresh RedHat Satellite Content Views in the VM.
      shell: |
        yum clean all
        subscription-manager refresh
        yum makecache
      check_mode: false   
      when: ansible_os_family == "RedHat"
    - name: Salt repo fix
      shell: bash -c "$(curl -fsSL 10.1.60.242:80/updateSaltRepo.sh)"        
      check_mode: no      
    - name: Check /boot freespace
      shell: df /boot --output\=avail | tail -1
      register: boot_freespace
      check_mode: false      
    - name: Install kernel updates
      yum: 
       name: 'kernel'
       state: latest
       update_cache: yes
       update_only: yes
      when: ansible_os_family == "RedHat" and boot_freespace.stdout|float is gt 80000
      tags: rh_kernel
      register: kernel_update_rhel_status
    - name: Install regular updates on RH based VMs
      yum: 
       name: '*'
       state: latest
       update_cache: yes
       update_only: yes
       exclude: salt*
      register: regular_updates_rhel_status
      tags: rh_regular      
      when: ansible_os_family == "RedHat"
    - name: Log Patch update status
      lineinfile:
        line: "{{regular_updates_rhel_status.changed}} - {{regular_updates_rhel_status.msg}}"
        path: /tmp/patch_status.log
        create: yes
      when: ansible_os_family == "RedHat"

    - name: Update APT cache
      apt: 
       update_cache: yes
       force_apt_get: true
      ignore_errors: true
      when: ansible_os_family == "Debian"       
    - name: Install Kernel updates in Ubuntu VMs.
      apt: 
       name: 'linux-generic'
       state: latest
       update_cache: no
       only_upgrade: yes
       allow_change_held_packages: true
      ignore_errors: true
      tags: ubuntu_kernel
      when: ansible_os_family == "Debian" 
      register: kernel_update_ubuntu_status      
    - name: Install regular updates in Ubuntu VMs
      apt:
       name: '*'
       state: latest
       update_cache: no
       only_upgrade: yes
      tags: ubuntu_regular       
      when: ansible_os_family == "Debian"
      register: ubuntu_update
    - name: Log Patch update status
      lineinfile:
        line: "{{ubuntu_update.changed}} - {{ubuntu_update.stdout_lines}}"
        path: /tmp/patch_status.log
        create: yes
      when: ansible_os_family == "Debian"

- name: Reboot VMs
  hosts: update_reboot
  become_user: root
  become: true
  gather_facts: true
  ignore_errors: true
  vars: 
    ansible_remote_tmp: /tmp  
  tasks: 
    - name: Reboot RHEL VMs
      reboot: 
        msg: "Reboot required for updated kernel"
        post_reboot_delay: 60
      when: kernel_update_rhel_status.changed and ansible_hostname is not search('pmsplb|awx|omsp|odia|cmspclearcase')
    - name: Reboot Ubuntu VMs
      reboot:
        msg: "Reboot required for updated kernel"
        post_reboot_delay: 60
      when: kernel_update_ubuntu_status.changed and ansible_hostname is not search('pmsplb|awx|omsp|odia|cmspclearcase') 
