---
#**************************************************************

# Script Name: patch_history.yml

# Description: This script will check for most recent patching activity in Ubuntu based VMs

# Author: Raghu Sundaram

# Organization: Harman

#**************************************************************
- name: Check apt history
  hosts: all
  strategy: free  
  gather_facts: true
  become_user: root
  become: true
  ignore_errors: yes
  tasks: 
############################################################################################################
# This will check for most recent patching activity  #
############################################################################################################

    - name: check apt history
      shell: tail /var/log/apt/history.log | grep Date
      register: patching_status
      when: ansible_os_family == "Debian"
    - name: print the results
      debug:
        var: patching_status.stdout_lines