---
# This playbook is to check for updates in both RHEL and Ubuntu VMs.
# playbook name: Linux_Register_Dev_Satellite_Patching-v3.yaml
# Author: Raghu Sundaram
# Organization: Harman

- name: Install updates in OMSP Production RedHat based VMs
  hosts: rhel
  become_user: root
  become: true
  gather_facts: false
  vars: 
    ansible_remote_tmp: /tmp
  ignore_errors: true
  tasks:
    - name: Install kernel updates
      yum: 
       name: 'kernel'
       state: latest
       update_cache: yes
       update_only: yes
      when: boot_freespace.stdout|float is gt 80000
      register: kernel_update_rhel_status
    - name: Install regular updates on RH based VMs
      yum: 
       name: '*'
       state: latest
       update_cache: yes
       update_only: yes
       exclude: salt*       
      register: regular_updates_rhel_status
    - name: Log Patch update status
      lineinfile:
        line: "{{regular_updates_rhel_status.changed}} - {{regular_updates_rhel_status.msg}}"
        path: /tmp/patch_status.log
        create: yes